<a href="https://colab.research.google.com/github/kavi02870-cmd/Machine-Learning-in-90-days/blob/master/day26-ordinal-encoding/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv('customer.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   gender     50 non-null     object
 2   review     50 non-null     object
 3   education  50 non-null     object
 4   purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [10]:
df.shape

(50, 5)

# New Section

In [ ]:
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
10   98  Female     Good        UG       Yes
9    74    Male     Good        UG       Yes
48   39  Female     Good        UG       Yes
30   73    Male  Average        UG        No

In [11]:
df = df.iloc[:,2:]

In [ ]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,[0,2]],df.iloc[:,-1],test_size=0.2)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
X_train

     review purchased
8   Average        No
26     Poor        No
3      Good        No
45     Poor       Yes
20  Average       Yes
43     Poor        No
31     Poor       Yes
4   Average        No
2      Good        No
5   Average       Yes
16     Poor       Yes
48     Good       Yes
13  Average        No
15     Poor        No
30  Average        No
9      Good       Yes
49     Good        No
34  Average        No
29  Average       Yes
1      Poor        No
44  Average        No
33     Good       Yes
40     Good        No
46     Poor        No
18     Good        No
14     Poor       Yes
6      Good        No
7      Poor       Yes
27     Poor        No
11     Good       Yes
19     Poor       Yes
12     Poor        No
22     Poor       Yes
28     Poor        No
42     Good       Yes
23     Good        No
25     Good        No
35     Poor       Yes
47     Good       Yes
41     Good       Yes

In [24]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [27]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['No','Yes']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['No', 'Yes']])

In [28]:
X_train = oe.transform(X_train)

In [ ]:
X_train

array([[0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.]])

In [29]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['No', 'Yes'], dtype=object)]

In [ ]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le = LabelEncoder()

In [32]:
le.fit(y_train)

LabelEncoder()

In [33]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [34]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [35]:
y_train

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1])